### ISSUE TITLE
Exception when running benchmarks_analyser.py 

### ISSUE THREAD

**Issue by scottyab** [dotanuki-labs/gradle-profiler-pttest#166] opened 2022-03-16 13:23 UTC
Hi @ubiratansoares, thanks for the talk and this library. I'm trying to get it up and running to run a fairly simple benchmark comparison to see if Gradle 7.2 and AGP 7.1.2 has any build speed increase for `app:assembleDebug`. I've generated the benchmarks using gradle-profiler. 

I've installed gradle-profiler-pttest via pip and attempting to run `gradle-profiler-pttest -b profile-out-7/benchmark.csv -m profile-out-8/benchmark.csv ` but getting the following error. 

```
/usr/local/lib/python3.9/site-packages/outdated/utils.py:14: OutdatedPackageWarning: The package pingouin is out of date. Your version is 0.3.8, the latest is 0.5.1.
Set the environment variable OUTDATED_IGNORE=1 to disable these warnings.
  return warn(
ERROR:root:Error when runnig analyser
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/gradle_profiler_pttest/benchmarks_analyser.py", line 16, in analyse
    stats = ttest(baseline.builds, modified.builds, paired=True, tail='greater').round(3)
  File "/usr/local/lib/python3.9/site-packages/pingouin/parametric.py", line 186, in ttest
    from scipy.stats.stats import (_unequal_var_ttest_denom,
ImportError: cannot import name '_unequal_var_ttest_denom' from 'scipy.stats.stats' (/usr/local/lib/python3.9/site-packages/scipy/stats/stats.py)
ERROR:root:An exception occurred
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/gradle_profiler_pttest/benchmarks_analyser.py", line 16, in analyse
    stats = ttest(baseline.builds, modified.builds, paired=True, tail='greater').round(3)
  File "/usr/local/lib/python3.9/site-packages/pingouin/parametric.py", line 186, in ttest
    from scipy.stats.stats import (_unequal_var_ttest_denom,
ImportError: cannot import name '_unequal_var_ttest_denom' from 'scipy.stats.stats' (/usr/local/lib/python3.9/site-packages/scipy/stats/stats.py)
```

>When running this tool on MacOS Catalina or newer, [please check instructions](https://docs.scipy.org/doc/scipy/reference/building/macosx.html) in order to have SciPy properly installed in your local machine.

I saw the above in the readme, however the link is broken, but after a bit of googling I found this command to install  `brew install numpy scipy ipython jupyter` via https://scipy.org/install/  and scipy seems to be installed unless there someother configuration needed? 

System: 

* macOS Big Sur 11.6.4
* Java 11
* Python 3.9

I'm not experienced in python/pip so it could be something simple I'm missing or perhaps it's some incompatibility with newer macOS?  Thanks

**Comment by ubiratansoares** [comment] 2022-03-20 21:26
Hi @scottyab 

I'm not maintaining this project anymore since I came with a better solution to extract outcomes (still with Python and still on top of scipy) and since I realized that Pingouin changed a couple of API since version 0.5.x. I'm about to publish such solution as open-source in the upcoming weeks.

Meanwhile, in order to mitigate this type of issues with regarding local environment + local Python + Scipy + etc, I've added a [Dockerfile](https://github.com/dotanuki-labs/gradle-profiler-pttest/blob/master/Dockerfile) in this project, which can be used to run this tool in a reproducible way. Let me know if you need support building and running this image locally.

**Comment by ubiratansoares** [comment] 2022-04-05 20:23
Hi @scottyab 

I'll close this issue since I'm finally deprecating/archiving this project.

As an overview on how I've been working with this very same problem recently - as I've mentioned above - but with different tools : I realised that [Google Colab](https://research.google.com/colaboratory/) and [Jupyter Notebooks](https://jupyter.org/) offer a really handy social/collaborative solution on top of SciPy, Pandas and other goodies from the Python Data Scientist tool belt.

Hence, nowadays I've been working exclusively with Colab when dealing with Gradle benchmarks. Other (Android) Engineers just need the Web Browser to access and interact with outcomes of any analysis I perform, it is much easier for them and for me, and we have everything we are used to have from Google Workspace tools like Docs for free (commenting system, sharing system, etc).

I really recommend you to have a look on this. :)

**Closed by ubiratansoares** 2022-04-05 20:23 UTC
